// This file is generated by Slice Machine. Update with care!

import Carousel from './Carousel';
import CodeBlock from './CodeBlock';
import Content from './Content';
import Fullwidthimage from './Fullwidthimage';
import Legal from './Legal';
import Masonrygrid from './Masonrygrid';
import MediaPlayer from './MediaPlayer';
import Quote from './Quote';
import SecondaryButton from './SecondaryButton';
import Twitter from './Twitter';

export {
	Carousel,
	CodeBlock,
	Content,
	Fullwidthimage,
	Legal,
	Masonrygrid,
	MediaPlayer,
	Quote,
	SecondaryButton,
	Twitter,
};

export const components = {
	carousel: Carousel,
	code_block: CodeBlock,
	content: Content,
	fullwidthimage: Fullwidthimage,
	legal: Legal,
	masonrygrid: Masonrygrid,
	media_player: MediaPlayer,
	quote: Quote,
	secondary_button: SecondaryButton,
	twitter: Twitter,
};
