// This file is generated by Slice Machine. Update with care!

import Callout from './Callout';
import Content from './Content';
import Fullwidthimage from './Fullwidthimage';
import Masonrygrid from './Masonrygrid';

export {
	Callout,
	Content,
	Fullwidthimage,
	Masonrygrid,
};

export const components = {
	callout: Callout,
	content: Content,
	fullwidthimage: Fullwidthimage,
	masonrygrid: Masonrygrid,
};
